/*
 * This source code has been generated by blanco Framework.
 */
package blanco.db.common.message;

/**
 * blancoDb の共通的なプラグインメッセージ。
 */
public class BlancoDbCommonPluginMessage {
    /**
     * A resource bundle class that is used internally to make messages correspond to property files.
     */
    protected final BlancoDbCommonPluginMessageResourceBundle fBundle = new BlancoDbCommonPluginMessageResourceBundle();

    /**
     * Gets the string of message definition ID [BlancoDbCommonPlugin] and key [MBDBCMI01].
     *
     * No.1:
     * String [blancoDb プラグインは以下のように利用してください。\n  1.Java プロジェクト内で利用してください\n    blancoDb のソースコード自動生成は、Java プロジェクト内で実行してください。\n  2.「ライブラリー」に JDBC ドライバの jar ファイルを追加してください\n    プロジェクトの「プロパティー」-&gt;「Java のビルド・パス」の「ライブラリー」に\n    JDBC ドライバの jar ファイルを追加してください。\n  ※これらは、ソースコード生成をおこなう場合の制限です。\n    生成されたソースコードの利用時には、関係ありません。]
     *
     * @return Message string.
     */
    public String getMbdbcmi01() {
        return fBundle.getMbdbcmi01();
    }

    /**
     * Gets the string of message definition ID [BlancoDbCommonPlugin] and key [MBDBCMC01].
     *
     * No.3:
     * String [接続チェック失敗]
     *
     * @return Message string.
     */
    public String getMbdbcmc01() {
        return fBundle.getMbdbcmc01();
    }

    /**
     * Gets the string of message definition ID [BlancoDbCommonPlugin] and key [MBDBCMC02].
     *
     * No.4:
     * String [指定のJDBCドライバ({0})の読み込みに失敗しました。\n\n該当の JDBC ドライバを読み込めるように設定変更が必要である可能性があります。\n以下の点を確認してください。\n 1.Java プロジェクト内で利用してください\n   blancoDb のソースコード自動生成は、Java プロジェクト内で実行して\n   ください。\n 2.「ライブラリー」に JDBC ドライバの jar ファイルを追加してください\n   プロジェクトの「プロパティー」-&gt;「Java のビルド・パス」の「ライブラリー」\n   に JDBC ドライバの jar ファイルを追加してください。]
     *
     * @param arg0 Value of the replacement string {0}.
     * @return Message string.
     */
    public String getMbdbcmc02(final String arg0) {
        if (arg0 == null) {
            throw new IllegalArgumentException("The parameter [arg0] of the method [getMbdbcmc02] has been given null. However, null cannot be given to this parameter.");
        }

        return fBundle.getMbdbcmc02(arg0);
    }
}
